spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?createDatabaseIfNotExist=true
    username: root
    password: felipedev55
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false